// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsUD_FXh-D4fgyFKXlkNBhULf_nF0zgLw',
    appId: '1:893950515224:web:0806d3aa4c75c13c824b6d',
    messagingSenderId: '893950515224',
    projectId: 'cooknote-48e17',
    authDomain: 'cooknote-48e17.firebaseapp.com',
    storageBucket: 'cooknote-48e17.firebasestorage.app',
    measurementId: 'G-PJSQ5RVYYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMqSFvbQaVRsEEou-1H906RpPAAdHQtMY',
    appId: '1:893950515224:android:24c748f7a587bee1824b6d',
    messagingSenderId: '893950515224',
    projectId: 'cooknote-48e17',
    storageBucket: 'cooknote-48e17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5xP1qLaZmCAoweR6yesajXqWBA7vWLKw',
    appId: '1:893950515224:ios:f08b4d61d5b953c4824b6d',
    messagingSenderId: '893950515224',
    projectId: 'cooknote-48e17',
    storageBucket: 'cooknote-48e17.firebasestorage.app',
    iosBundleId: 'com.example.cooknote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5xP1qLaZmCAoweR6yesajXqWBA7vWLKw',
    appId: '1:893950515224:ios:f08b4d61d5b953c4824b6d',
    messagingSenderId: '893950515224',
    projectId: 'cooknote-48e17',
    storageBucket: 'cooknote-48e17.firebasestorage.app',
    iosBundleId: 'com.example.cooknote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsUD_FXh-D4fgyFKXlkNBhULf_nF0zgLw',
    appId: '1:893950515224:web:785832ccbb0fd5c4824b6d',
    messagingSenderId: '893950515224',
    projectId: 'cooknote-48e17',
    authDomain: 'cooknote-48e17.firebaseapp.com',
    storageBucket: 'cooknote-48e17.firebasestorage.app',
    measurementId: 'G-50PX4ZSNMR',
  );
}
